//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebDavWhs {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebDavWhs.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebDAV for WHS.
        /// </summary>
        internal static string AddInName {
            get {
                return ResourceManager.GetString("AddInName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configure WebDAV.
        /// </summary>
        internal static string ConfigureWebdav {
            get {
                return ResourceManager.GetString("ConfigureWebdav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter an alias name for the virtual directory..
        /// </summary>
        internal static string Error_VirtDirName {
            get {
                return ResourceManager.GetString("Error_VirtDirName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://localhost/{0}/.
        /// </summary>
        internal static string PlaceholderUrl {
            get {
                return ResourceManager.GetString("PlaceholderUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The virtual directory or a web application with the alias &apos;{0}&apos; already exists. Do you want to re-create the virtual directory?.
        /// </summary>
        internal static string Question_Overwite {
            get {
                return ResourceManager.GetString("Question_Overwite", resourceCulture);
            }
        }
    }
}
